### ISSUE TITLE
Is there any example here?

### ISSUE THREAD

**Issue by huyanping** [ratchetphp/RFC6455#2]

**Comment by cboden** [comment]
This library is still in beta as we're working out the API but there's a couple implementations you can check out: 

* [Ratchet's implementation](https://github.com/ratchetphp/Ratchet/tree/0.4-wip/psr7)
* [Autobahn test server](https://github.com/ratchetphp/RFC6455/blob/psr7/tests/ab/startServer.php)
* [Autobahn test client](https://github.com/ratchetphp/RFC6455/blob/psr7/tests/ab/clientRunner.php)

**Comment by huyanping** [comment]
Hi~
   I am trying to write a safe websocket protocol package which is independent of the socket server. It's hard and this package is helpful. I mean that I can use it with any socket server to make a websocket server. Thanks for the examples.
