### ISSUE TITLE
249999999.75 is not a valid maxFramePayloadSize

### ISSUE THREAD

**Issue by ondrejmirtes** [ratchetphp/RFC6455#41]
I'm getting this error message:

```
249999999.75 is not a valid maxFramePayloadSize
```

From this piece of code:

https://github.com/ratchetphp/RFC6455/blob/c8651c7938651c2d55f5d8c2422ac5e57a183341/src/Messaging/MessageBuffer.php#L126-L128

I think there should be some value checking after dividing the system memory limit by 4.

**Comment by cboden** [comment]
fixed in #53
