### ISSUE TITLE
Missing support for `guzzlehttp/psr7:^2.0`

### ISSUE THREAD

**Issue by iPurpl3x** [ratchetphp/RFC6455#45]
The package `guzzlehttp/psr7 v2.0.0` was released on the 2021-06-30. Could you consider adding support for this version?

At this time, people using `ratchet/rfc6455` need to downgrade to `guzzlehttp/psr7:^1.0`.

**Comment by iPurpl3x** [comment]
(cc @cboden)

**Comment by shehi** [comment]
We need this guys.

**Comment by cboden** [comment]
Merged in #47
